apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-nginx
  labels:
    app: web-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-nginx
  template:
    metadata:
      labels:
        app: web-nginx
    spec:
      containers:
        - name: flask
          image: jvicmar95/proyecto-zabbix:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000   # 👈 Cambiado de 80 a 5000

---
apiVersion: v1
kind: Service
metadata:
  name: web-nginx
spec:
  selector:
    app: web-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000            # 👈 Muy importante: apunta al puerto del contenedor
  type: LoadBalancer
